//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Tue 22-Nov-2011 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package main;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Date implements EvaluatePP {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=day KEEP=NO
  public volatile Integer day = null;
// ***** VDMTOOLS END Name=day

// ***** VDMTOOLS START Name=month KEEP=NO
  public volatile Integer month = null;
// ***** VDMTOOLS END Name=month

// ***** VDMTOOLS START Name=year KEEP=NO
  public volatile Integer year = null;
// ***** VDMTOOLS END Name=year

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=DateSentinel KEEP=NO
  class DateSentinel extends Sentinel {

    public final int Date = 0;

    public final int nr_functions = 1;


    public DateSentinel () throws CGException {}


    public DateSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=DateSentinel
;

// ***** VDMTOOLS START Name=evaluatePP KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new DateSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=Date KEEP=NO
  public Date () throws CGException {
    try {
      setSentinel();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Date


// ***** VDMTOOLS START Name=Date KEEP=NO
  public Date (final Integer d, final Integer m, final Integer y) throws CGException {

    try {
      setSentinel();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
    {

      day = UTIL.NumberToInt(UTIL.clone(d));
      month = UTIL.NumberToInt(UTIL.clone(m));
      year = UTIL.NumberToInt(UTIL.clone(y));
    }
  }
// ***** VDMTOOLS END Name=Date

}
;
